# Choose compiler:
CC=g++

# Build Directory:
BUILD=../build/

# Objects
OBJS=main.cpp Print.cpp Globals.cpp Narration.cpp

# Target : Dependancy
all:
	$(CC) -std=c++11 $(OBJS) -o $(BUILD)Ascencia_Origins.sh
