* ASCENCIA *

** Summary **

Ascencia: a planet lost in an unknown part of the cosmos.

Universe: real universe

Game idea: Players assume humans who have been brought to the world of Ascencia
through some sort of Portal or Wormhole. (exact mechanic to be more thoroughly 
thought through later!)

They land on this planet which has similarly brought many other species and weird 
creatures from other worlds, through the same method through which humans were 
brought here.

This is not known by the player until later; the idea is that it feels like a 
sandbox game, the lore slowly unfolds as gameplay progresses. Small lore hints can 
be dropped here and there through clues and dialogue with NPCs, etc.

Ascencia was brought into existence at the Big Bang, and is essentially the centre of
all power in the universe. Many advanced species have been seeking its' secrets,
and the humans who have been brought here suddenly are catapulted into the middle of
this. Of course, players don't know this. They don't realise the importance of the
world until basically the end of the story.

The almighty cosmic energy that brought Ascencia into existence means that most life
forms on it have access to magical powers (cue "The Magic System!")

Throughout the world are these magical crystals which spew energy into the atmosphere.
These are fonts are energy and mana, and creatures near them can absorb some of this
energy, they can heal at accelerated rates, learn things, etc etc. Useful for game
mechanics!

** History **

In the beginning there was an almighty explosion. All the matter in the universe
converged into one singular location all at once. As the compressed matter fused
into a billion trillion black holes, it simultaneously expelled all energy in an
outward direction, leading to the current shape of the universe.

As stars were born and died on the outer spiral arms of the universe, planets
came into existence and were swallowed up by other, larger planets, stars, and
black holes, all the while, at the centre of the big bang, one star fades and
settles. With its' energy expelled at higher velocity than any other object in
existence, it formed matter on its surface not to be found anywhere else in the
entire universe. This matter is formed from the ashes of destruction and creation;
from the ashes of the previous universe that existed, and the spark of life of the
currently existing universe, in which we currently now reside.

** The Existaxnt **

It is perhaps obvious at this point that there existed, innumerable years ago, a
universe before our current one; and we are built of the same matter that was once
said previous universe.

Matter is not the same now as it once was; the previous universe may not have had
the same construction of atoms and particles; our periodic table of elements
(although incomplete) does not represent the matter that existed in a previous
universe.

It also stands to reason, therefore, that there was also life in previous incarnations
of the universe. There have been infinite universes throughout all of time that has
ever existed in all of its many forms, and therefore also an infinite number of life
forms.

Of all, there has been only one conscious species which has existed after its own
universe was swallowed up the force of its own residual energy, The Existant.
They existed on the outer edge of space, far out of reach of the cosmic power
bringing all matter to the centre to be chewed up and spit back out.

The Existant had evolved to the point of being able to absorb energy from almost
any source in order to survive - something which no other species had ever achieved
before or after.

//As far as The Existant go for game design, I'm not sure how to approach this; but
the idea of them came into my head and they seemed like a pretty cool idea. Maybe
have to experiment with some ideas! Possibly the antagonists want to try to harness
the power of Ascencia for their own gains, but in doing so would basically undo all
of creation and demolish the universe - and The Existant might intervene somehow.//

** The Kirukandji **

   // Gameplay wise, these are the main antagonists.
