* Ascencia: First Encounter *
** Chapter One **
Christopher woke with a start. He sat where he was for a few moments massaging his forehead,
which was damp with sweat. The terminal which had woken him with its piercing alarm tone sat silently
flashing red lights at him. Although he had already correctly guessed the cause of his sudden rude awakening,
Christopher still glanced over the alert codes which read, "ANOMALY DETECTED", and, "CREW INPUT REQUIRED", with
every other flash of the alert panel. He took in a few slow, purposeful lungs of recycled air before using the 
panel to inspect the Computer's report more closely.

He didn't really expect anything spectacular. It never was, in the field. Yes, he thought bitterly to himself, the
academy had promised exciting new worlds and fascinating new discoveries, and indeed there were new worlds and plenty
of discoveries, but none of them had been even slightly exciting - unless you counted the strange liquid substance they
had discovered a couple of months ago, and after several exciting minutes in the lab, realized that it was in fact the
remains of last nights dinner. After digestion. Carey, the navigation officer, had slowed down their velocity so as to
sling shot around a nearby exo-planet, and so their debris had caught up with them.
